[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[build.processing]
  skip_processing = false

[secrets]
  SECRETS_SCAN_OMIT_KEYS = ["SUPABASE_ANON_KEY"]
